<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>false</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- Single File & Trimming -->
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishTrimmed>false</PublishTrimmed>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    
    <!-- Metadata -->
    <Authors>Volfheim</Authors>
    <Product>Smart Audio Switcher</Product>
    <Description>System utility for smart audio device switching</Description>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>3.0.7</Version>
    <AssemblyVersion>3.0.7</AssemblyVersion>
    <FileVersion>3.0.7</FileVersion>
    <Copyright>Copyright © 2026 Volfheim</Copyright>
  </PropertyGroup>


  <ItemGroup>
    <Resource Include="app.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.3" />
  </ItemGroup>

</Project>
